[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
stake_proxy = "StakePPyu7cgbWngmEhW5Gr86D9x1HZoseKy2JFTNbP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
